export const ENDPOINTS = {
  USER_ROUTE: {
    REGISTER: "/register",
    LOGIN: "/login",
    VERIFY: "/verify-otp",
    OTP_REQUEST: "/resend-otp",
    ALL_PRODUCT_LIST: "/all-products-list",
    USER_PROFILE: "/profile",
  },
  ADMIN_ROUTE: {
    DASHBOARD: "/dashboard",
    USERS: "/users",
    ORDERS: "/orders",
    REVENUE: "/reports/revenue",
    UPDATE_USER_STATUS: "/users/:userId/status",
    // Category Routes
    SUPER_CATEGORY: "/super-category",
    SUPER_CATEGORIES: "/super-categories",
    SUPER_CATEGORY_BY_ID: "/super-category/:id",
    UPDATE_SUPER_CATEGORY: "/super-category/:id",
    DELETE_SUPER_CATEGORY: "/super-category/:id",
    CATEGORY: "/category",
    CATEGORIES: "/categories",
    CATEGORY_BY_ID: "/category/:id",
    UPDATE_CATEGORY: "/category/:id",
    DELETE_CATEGORY: "/category/:id",
    SUB_CATEGORY: "/sub-category",
    SUB_CATEGORIES: "/sub-categories",
    SUB_CATEGORY_BY_ID: "/sub-category/:id",
    UPDATE_SUB_CATEGORY: "/sub-category/:id",
    DELETE_SUB_CATEGORY: "/sub-category/:id",
    PRODUCT_CATEGORY: "/product-category",
    PRODUCT_CATEGORIES: "/product-categories",
    PRODUCT_CATEGORY_BY_ID: "/product-category/:id",
    UPDATE_PRODUCT_CATEGORY: "/product-category/:id",
    DELETE_PRODUCT_CATEGORY: "/product-category/:id",
    // Product Routes
    CREATE_PRODUCT: "/create",
    ALL_PRODUCTS: "/all-list",
    PRODUCT_BY_ID_AND_ROLES: "/all",
    PRODUCT_BY_ID: "/:id",
    UPDATE_PRODUCT: "/:id",
    DELETE_PRODUCT: "/:id",
  },
  CART_ROUTE: {
    ADD_ITEM: "/add",
    GET_CART: "/",
    UPDATE_CART_ITEM: "/:cartItemId",
    REMOVE_ITEM: "/:cartItemId",
    CLEAR_CART: "/",
    VALIDATE_CART: "/validate",
  },
  ORDER_ROUTE: {
    CREATE_ORDER: "/",
    GET_ORDERS: "/",
    GET_ORDER_BY_STATUS: "/status/:status",
    GET_ORDER_BY_ID: "/:orderId",
    UPDATE_ORDER: "/:orderId",
    CANCEL_ORDER: "/:orderId/cancel",
  },
  ADDRESS_ROUTE: {
    CREATE_ADDRESS: "/",
    GET_ADDRESSES: "/",
    GET_DEFAULT_ADDRESS: "/default/:type",
    GET_ADDRESS_BY_ID: "/:addressId",
    UPDATE_ADDRESS: "/:addressId",
    SET_ADDRESS_AS_DEFAULT: "/:addressId/default",
    DELETE_ADDRESS: "/:addressId",
  },
  PAYMENT_ROUTE: {
    INITIATE_PAYMENT: "/initiate",
    PAYMENT_CALLBACK: "/:paymentId/callback",
    STRIPE_CALLBACK: "/:paymentId/stripe/callback",
    PAYPAL_CALLBACK: "/:paymentId/paypal/callback",
    REFUND_PAYMENT: "/:paymentId/refund",
    GET_ORDER_PAYMENTS: "/order/:orderId",
    GET_PAYMENT: "/:paymentId",
  },
  REVIEW_ROUTE: {
    CREATE_REVIEW: "/",
    GET_REVIEWS: "/product/:productId",
    GET_USER_REVIEWS: "/user",
    UPDATE_REVIEW: "/:reviewId",
    DELETE_REVIEW: "/:reviewId",
  },
  DELIVERY_ROUTE: {
    GET_DELIVERY_DASHBOARD: "/dashboard",
    GET_ASSIGNED_ORDERS: "/orders",
    UPDATE_DELIVERY_STATUS: "/orders/:orderId/status",
    GET_DELIVERY_ROUTE: "/route",
  },
  SHIPPING_ROUTE: {
    UPDATE_SHIPPING_STATUS: "/:shippingId/status",
    GET_SHIPPING_INFO: "/order/:orderId",
    TRACK_SHIPMENT: "/track/:trackingNumber",
    GET_DELIVERY_ASSIGNMENTS: "/delivery/assignments",
  },
  VENDOR_ROUTE: {
    GET_VENDOR_DASHBOARD: "/dashboard",
    GET_VENDOR_PRODUCTS: "/products",
    GET_VENDOR_ORDERS: "/orders",
    UPDATE_ORDER_STATUS: "/orders/:orderId/status",
    GET_INVENTORY_REPORT: "/inventory/report",
  },
  INVENTORY_ROUTE: {
    CREATE_INVENTORY: "/create",
    GET_INVENTORY: "/product/:productId",
    UPDATE_INVENTORY: "/product/:productId",
    RESTOCK_INVENTORY: "/restock/:productId",
    GET_LOW_STOCK: "/low-stock",
    GET_OUT_OF_STOCK: "/out-of-stock",
    GET_INVENTORY_REPORT: "/report",
  },
} as const;
